'use strict';

angular.module('appApp').constant('missingCountries',[
  { id: 'HND_Honduras',value: 'Honduras',missing: ['_adm3']},
  { id: 'HKG_Hongkong',value: 'Hongkong',missing: ['_adm2','_adm3']},
  { id: 'HUN_Hungary',value: 'Hungary',missing: ['_adm2','_adm3']},
  { id: 'ISL_Iceland',value: 'Iceland',missing: ['_adm3']},
  { id: 'IDN_Indonesia',value: 'Indonesia',missing: ['_adm3']},
  { id: 'IRN_Iran',value: 'Iran',missing: ['_adm3','_adm3']},
  { id: 'IRL_Ireland',value: 'Ireland',missing: ['_adm2','_adm3']},
  { id: 'IMN_Isle of Man',value: 'Isle of Man',missing: ['_adm1','_rails','_water_areas_dcw']},
  { id: 'ISR_Israel',value: 'Israel',missing: ['_adm3']},
  { id: 'JAM_Jamaica',value: 'Jamaica',missing: ['_adm3']},
  { id: 'JEY_Jersey',value: 'Jersey',missing: ['_adm1','_adm3']},
  { id: 'JOR_Jordan',value: 'Jordan',missing: ['_adm3']},
  { id: 'JPN_Japan',value: 'Japan',missing: ['_adm3']},
  { id: 'KAZ_Kazakhstan',value: 'Kazakhstan',missing: ['_adm3']},
  { id: 'KIR_Kiribati',value: 'Kiribati',missing: ['_adm3']},
  { id: 'KO-_Kosova',value: 'Kosova',missing: ['_adm1','_adm1','_adm2','_water_areas_dcw','_rails']},
  { id: 'KWT_Kuwait',value: 'Kuwait',missing: ['_adm2','_adm3']},
  { id: 'KGZ_Kyrgyzstan',value: 'Kyrgyzstan',missing: ['_adm3']},
  { id: 'LAO_Laos',value: 'Laos',missing: ['_adm3']},
  { id: 'LVA_Latvia',value: 'Latvia',missing: ['_adm3']},
  { id: 'LSO_Lesotho',value: 'Lesotho',missing: ['_adm3','_adm2']},
  { id: 'LBN_Lebanon',value: 'Lebanon',missing: ['_adm3']},
  { id: 'LBY_Libya',value: 'Libya',missing: ['_adm2']},
  { id: 'LIE_Liechtenstein',value: 'Liechtenstein',missing: ['_adm3']},
  { id: 'LTU_Lithuania',value: 'Lithuania',missing: ['_adm3']},
  { id: 'LUX_Luxembourg',value: 'Luxembourg',missing: ['_adm3']},
  { id: 'MAC_Macao',value: 'Macao',missing: ['_adm2','_adm3']},
  { id: 'MKD_Macedonia',value: 'Macedonia',missing: ['_adm3']},
  { id: 'MYS_Malaysia',value: 'Malaysia',missing: ['_adm1']},
  { id: 'MDV_Maldives',value: 'Maldives',missing: ['_adm1','_adm3']},
  { id: 'MLT_Malta',value: 'Malta',missing: ['_adm3']},
  { id: 'MHL_Marshall Islands',value: 'Marshall Islands',missing: ['_adm3']},
  { id: 'MTQ_Martinique',value: 'Martinique',missing: ['_adm3']},
  { id: 'MRT_Mauritania',value: 'Mauritania',missing: ['_adm3']},
  { id: 'MUS_Mauritius',value: 'Mauritius',missing: ['_adm3']},
  { id: 'MYT_Mayotte',value: 'Mayotte',missing: ['_adm3']},
  { id: 'MEX_Mexico',value: 'Mexico',missing: ['_adm3']},
  { id: 'FSM_Micronesia,Federated States of ',value: 'Micronesia,Federated States of ',missing: ['_adm3']},
  { id: 'MDA_Moldova',value: 'Moldova',missing: ['_adm2','_adm3']},
  { id: 'MCO_Monaco',value: 'Monaco',missing: ['_adm3']},
  { id: 'MNG_Mongolia',value: 'Mongolia',missing: ['_adm3']},
  { id: 'MNE_Montenegro',value: 'Montenegro',missing: ['_adm1','_adm1']},
  { id: 'MSR_Montserrat',value: 'Montserrat',missing: ['_adm1','_adm3']},
  { id: 'NAM_Namibia',value: 'Namibia',missing: ['_adm3']},
  { id: 'NRU_Nauru',value: 'Nauru',missing: ['_adm3']},
  { id: 'NLD_Netherlands',value: 'Netherlands',missing: ['_adm3']},
  { id: 'ANT_Netherlands Antilles',value: 'Netherlands Antilles',missing: ['_adm3']},
  { id: 'NCL_New Caledonia',value: 'New Caledonia',missing: ['_adm3']},
  { id: 'NIC_Nicaragua',value: 'Nicaragua',missing: ['_adm3']},
  { id: 'NGA_Nigeria',value: 'Nigeria',missing: ['_adm3']},
  { id: 'NIU_Niue',value: 'Niue',missing: ['_adm2','_adm3']},
  { id: 'NFK_Norfolk Island',value: 'Norfolk Island',missing: ['_adm1','_adm3']},
  { id: 'PRK_North Korea',value: 'North Korea',missing: ['_adm3']},
  { id: 'MNP_Northern Mariana Islands',value: 'Northern Mariana Islands',missing: ['_adm3']},
  { id: 'NOR_Norway',value: 'Norway',missing: ['_adm3']},
  { id: 'OMN_Oman',value: 'Oman',missing: ['_adm3']},
  { id: 'PLW_Palau',value: 'Palau',missing: ['_adm3']},
  { id: 'PSE_Palestina',value: 'Palestina',missing: ['_adm3']},
  { id: 'PNG_Papua New Guinea',value: 'Papua New Guinea',missing: ['_adm3']},
  { id: 'PRY_Paraguay',value: 'Paraguay',missing: ['_adm3']},
  { id: 'PCN_Pitcairn Islands',value: 'Pitcairn Islands',missing: ['_adm1','_adm3']},
  { id: 'POL_Poland',value: 'Poland',missing: ['_adm3']},
  { id: 'PRI_Puerto Rico',value: 'Puerto Rico',missing: ['_adm2','_adm3']},
  { id: 'QAT_Qatar',value: 'Qatar',missing: ['_adm3']},
  { id: 'REU_Reunion',value: 'Reunion',missing: ['_adm3']},
  { id: 'ROU_Romania',value: 'Romania',missing: ['_adm3']},
  { id: 'RUS_Russian Federation',value: 'Russian Federation',missing: ['_adm3']},
  { id: 'RWA_Rwanda',value: 'Rwanda',missing: ['_adm3']},
  { id: 'SHN_Saint Helena',value: 'Saint Helena',missing: ['_adm3']},
  { id: 'KNA_Saint Kitts and Nevis',value: 'Saint Kitts and Nevis',missing: ['_adm2','_adm3']},
  { id: 'SPM_Saint Pierre and Miquelon',value: 'Saint Pierre and Miquelon',missing: ['_adm3']},
  { id: 'VCT_Saint Vincent and the Grenadines',value: 'Saint Vincent and the Grenadines',missing: ['_adm3']},
  { id: 'WSM_Samoa',value: 'Samoa',missing: ['_adm3']},
  { id: 'SMR_San Marino',value: 'San Marino',missing: ['_adm2','_adm3']},
  { id: 'LCA_Santa Lucia',value: 'Santa Lucia',missing: ['_adm2']},
  { id: 'STP_Sao Tome and Principe',value: 'Sao Tome and Principe',missing: ['_adm2','_adm3']},
  { id: 'SAU_Saudi Arabia',value: 'Saudi Arabia',missing: ['_adm3']},
  { id: 'SRB_Serbia',value: 'Serbia',missing: ['_adm3']},
  { id: 'SYC_Seychelles',value: 'Seychelles',missing: ['_adm2']},
  { id: 'SGP_Singapore',value: 'Singapore',missing: ['_adm3']},
  { id: 'SVK_Slovakia',value: 'Slovakia',missing: ['_adm3']},
  { id: 'SLB_Solomon Islands',value: 'Solomon Islands',missing: ['_adm2','_adm3']},
  { id: 'SOM_Somalia',value: 'Somalia',missing: ['_adm3']},
  { id: 'ZAF_South Africa',value: 'South Africa',missing: ['_adm3']},
  { id: 'SGS_South Georgia and the South Sandwich Islands',value: 'South Georgia and the South Sandwich Islands',missing: ['_adm3']},
  { id: 'KOR_South Korea',value: 'South Korea',missing: ['_adm3']},
  { id: 'LKA_Sri Lanka',value: 'Sri Lanka',missing: ['_adm3']},
  { id: 'SJM_Svalbard and Jan Mayen',value: 'Svalbard and Jan Mayen',missing: ['_adm2']},
  { id: 'SUR_Suriname',value: 'Suriname',missing: ['_adm3']},
  { id: 'SJM_Svalbard and Jan Mayen',value: 'Svalbard and Jan Mayen',missing: ['_adm3']},
  { id: 'SWZ_Swaziland',value: 'Swaziland',missing: ['_adm2']},
  { id: 'SWE_Sweden',value: 'Sweden',missing: ['_adm3']},
  { id: 'CHE_Switzerland',value: 'Switzerland',missing: ['_adm2','_adm3']},
  { id: 'SYR_Syria',value: 'Syria',missing: ['_adm3']},
  { id: 'TWN_Taiwan',value: 'Taiwan',missing: ['_adm3']},
  { id: 'TLS_Timor-Leste',value: 'Timor-Leste',missing: ['_adm3']},
  { id: 'TGO_Togo',value: 'Togo',missing: ['_adm3']},
  { id: 'TKL_Tokelau',value: 'Tokelau',missing: ['_adm3']},
  { id: 'TON_Tonga',value: 'Tonga',missing: ['_adm3']},
  { id: 'TTO_Trinidad and Tobago',value: 'Trinidad and Tobago',missing: ['_adm2','_adm3']},
  { id: 'TUN_Tunisia',value: 'Tunisia',missing: ['_adm3']},
  { id: 'TUR_Turkey',value: 'Turkey',missing: ['_adm3']},
  { id: 'TKM_Turkmenistan',value: 'Turkmenistan',missing: ['_adm2','_adm3']},
  { id: 'TCA_Turks and Caicos Islands',value: 'Turks and Caicos Islands',missing: ['_adm3']},
  { id: 'TUV_Tuvalu',value: 'Tuvalu',missing: ['_adm3']},
  { id: 'UKR_Ukraine',value: 'Ukraine',missing: ['_adm3']},
  { id: 'ARE_United Arab Emirates',value: 'United Arab Emirates',missing: ['_adm2','_adm3']},
  { id: 'GBR_United Kingdom',value: 'United Kingdom',missing: ['_adm3']},
  { id: 'USA_United States',value: 'United States',missing: ['_adm3']},
  { id: 'UMI_United States Minor Outlying Island',value: 'United States Minor Outlying Island',missing: ['_adm3']},
  { id: 'URY_Uruguay',value: 'Uruguay',missing: ['_adm3']},
  { id: 'UZB_Uzbekistan',value: 'Uzbekistan',missing: ['_adm2','_adm3']},
  { id: 'VUT_Vanuatu',value: 'Vanuatu',missing: ['_adm2','_adm3']},
  { id: 'VAT_Vatican',value: 'Vatican',missing: ['_adm2']}
]);
