'use strict';

angular.module('appApp').constant('missingCountries',[
 { id:'AFG_Afghanistan', value:'Afghanistan', missing:['_adm3','_rails']},
 { id:'ALA_Åland Islands', value:'Åland Islands', missing:['_adm2','_adm3','_rails']},
 { id: "KAZ_Kazakhstan", value: "Kazakhstan", missing: ["_adm3"] }, 
 { id: "BMU_Bermuda", value: "Bermuda", missing: ["_adm3","_adm2"] }, 
 { id: "FLK_Falkland Islands", value: "Falkland Islands", missing: ["_rails","_roads","_water_areas_dcw","_adm2","_adm3"] }, 
 { id: "UZB_Uzbekistan", value: "Uzbekistan", missing: ["_adm3","_adm2"] }, 
 { id: "GTM_Guatemala", value: "Guatemala", missing: ["_adm3"] }, 
 { id: "BRB_Barbados", value: "Barbados", missing: ["_adm3","_adm2"] }, 
 { id: "TTO_Trinidad and Tobago", value: "Trinidad and Tobago", missing: ["_adm2","_adm3","_roads","_rails"] }, 
 { id: "TUV_Tuvalu", value: "Tuvalu", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "HUN_Hungary", value: "Hungary", missing: ["_adm3","_adm2"] }, 
 { id: "NLD_Netherlands", value: "Netherlands", missing: ["_adm3"] }, 
 { id: "COG_Congo,Republic of", value: "Congo,Republic of", missing: ["_adm3"] }, 
 { id: "FRO_Faroe Islands", value: "Faroe Islands", missing: ["_adm3","_rails"] }, 
 { id: "SGS_South Georgia and the South Sandwich Islands", value: "South Georgia and the South Sandwich Islands", missing: ["_adm3","_adm2","_adm1","_rails","_roads"] }, 
 { id: "VAT_Vatican", value: "Vatican", missing: ["_adm2","_adm3","_rails","_roads","_water_areas_dcw"] }, 
 { id: "IOT_British Indian Ocean Territory", value: "British Indian Ocean Territory", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "MCO_Monaco", value: "Monaco", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "CXR_Christmas Island", value: "Christmas Island", missing: ["_adm1","_adm2","_adm3","_water_areas_dcw"] }, 
 { id: "SGP_Singapore", value: "Singapore", missing: ["_adm1","_adm3","_water_areas_dcw"] }, 
 { id: "MNE_Montenegro", value: "Montenegro", missing: ["_adm3"] }, 
 { id: "TUR_Turkey", value: "Turkey", missing: ["_adm3","_adm2"] }, 
 { id: "KIR_Kiribati", value: "Kiribati", missing: ["_adm1","_adm2","_adm3","_water_areas_dcw","_rails","_roads"] }, 
 { id: "SHN_Saint Helena", value: "Saint Helena", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "UMI_United States Minor Outlying Island", value: "United States Minor Outlying Island", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "TLS_Timor-Leste", value: "Timor-Leste", missing: ["_adm3","_rails"] }, 
 { id: "FJI_Fiji", value: "Fiji", missing: ["_adm3"] }, 
 { id: "MLT_Malta", value: "Malta", missing: ["_adm3","_adm2","_roads","_water_areas_dcw"] }, 
 { id: "PRK_North Korea", value: "North Korea", missing: ["_adm3"] }, 
 { id: "PYF_French Polynesia", value: "French Polynesia", missing: ["_adm1","_adm2","_adm3","_roads","_water_areas_dcw"] }, 
 { id: "AZE_Azerbaijan", value: "Azerbaijan", missing: ["_adm3","_adm2"] }, 
 { id: "MNG_Mongolia", value: "Mongolia", missing: ["_adm3"] }, 
 { id: "CCK_Cocos Islands", value: "Cocos Islands", missing: ["_adm1","_adm2","_adm3","_rails","_roads","_water_areas_dcw"] }, 
 { id: "MSR_Montserrat", value: "Montserrat", missing: ["_adm1","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "ZMB_Zambia", value: "Zambia", missing: ["_adm3"] }, 
 { id: "KWT_Kuwait", value: "Kuwait", missing: ["_adm3","_adm2"] }, 
 { id: "KO-_Kosova", value: "Kosova", missing: ["_adm0","_adm1","_adm2","_adm3","_rails","_roads"] }, 
 { id: "URY_Uruguay", value: "Uruguay", missing: ["_adm3"] }, 
 { id: "TGO_Togo", value: "Togo", missing: ["_adm3"] }, 
 { id: "NIU_Niue", value: "Niue", missing: ["_adm3","_roads","_water_areas_dcw"] }, 
 { id: "MNP_Northern Mariana Islands", value: "Northern Mariana Islands", missing: ["_adm3","_adm2","_roads"] }, 
 { id: "BHS_Bahamas", value: "Bahamas", missing: ["_adm3","_adm2","_rails"] }, 
 { id: "HMD_Heard Island and McDonald Islands", value: "Heard Island and McDonald Islands", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "COM_Comoros", value: "Comoros", missing: ["_adm3","_adm2","_roads"] }, 
 { id: "KNA_Saint Kitts and Nevis", value: "Saint Kitts and Nevis", missing: ["_adm3","_adm2"] }, 
 { id: "TKL_Tokelau", value: "Tokelau", missing: ["_adm2","_adm3","_rails","_roads","_water_areas_dcw"] }, 
 { id: "IMN_Isle of Man", value: "Isle of Man", missing: ["_rails","_water_areas_dcw","_adm2","_adm3","_roads"] }, 
 { id: "NFK_Norfolk Island", value: "Norfolk Island", missing: ["_adm1","_adm3","_roads"] }, 
 { id: "JEY_Jersey", value: "Jersey", missing: ["_adm1","_adm2","_adm3","_roads"] }, 
 { id: "JOR_Jordan", value: "Jordan", missing: ["_adm3"] }, 
 { id: "PRY_Paraguay", value: "Paraguay", missing: ["_adm3"] }, 
 { id: "STP_Sao Tome and Principe", value: "Sao Tome and Principe", missing: ["_adm3","_adm2","_water_areas_dcw"] }, 
 { id: "ISL_Iceland", value: "Iceland", missing: ["_adm3","_rails"] }, 
 { id: "COK_Cook Islands", value: "Cook Islands", missing: ["_adm1","_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "GGY_Guernsey", value: "Guernsey", missing: ["_adm1","_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "SJM_Svalbard and Jan Mayen", value: "Svalbard and Jan Mayen", missing: ["_adm2","_adm3","_roads"] }, 
 { id: "TUN_Tunisia", value: "Tunisia", missing: ["_adm3"] }, 
 { id: "SAU_Saudi Arabia", value: "Saudi Arabia", missing: ["_adm3","_adm2"] }, 
 { id: "BHR_Bahrain", value: "Bahrain", missing: ["_adm3","_adm2","_rails"] }, 
 { id: "NRU_Nauru", value: "Nauru", missing: ["_adm2","_adm3","_rails","_roads","_water_areas_dcw"] }, 
 { id: "CYM_Cayman Islands", value: "Cayman Islands", missing: ["_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "ARE_United Arab Emirates", value: "United Arab Emirates", missing: ["_adm3","_adm2","_rails"] }, 
 { id: "CPV_Cape Verde", value: "Cape Verde", missing: ["_adm3","_rails","_water_areas_dcw"] }, 
 { id: "ABW_Aruba", value: "Aruba", missing: ["_adm1","_adm2","_adm3","_water_areas_dcw"] }, 
 { id: "ANT_Netherlands Antilles", value: "Netherlands Antilles", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "BRN_Brunei Darussalam", value: "Brunei Darussalam", missing: ["_adm3"] }, 
 { id: "MDV_Maldives", value: "Maldives", missing: ["_adm3","_adm2","_rails","_roads","_water_areas_dcw"] }, 
 { id: "VIR_Virgin Islands,U.S", value: "Virgin Islands,U.S", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "PLW_Palau", value: "Palau", missing: ["_adm3","_adm2","_rails","_water_areas_dcw"] }, 
 { id: "GRD_Grenada", value: "Grenada", missing: ["_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "BVT_Bouvet Island", value: "Bouvet Island", missing: ["_adm1","_adm2","_adm3","_rails","_roads","_water_areas_dcw"    ] }, 
 { id: "BGR_Bulgaria", value: "Bulgaria", missing: ["_adm3"] }, 
 { id: "TKM_Turkmenistan", value: "Turkmenistan", missing: ["_adm2","_adm3"] }, 
 { id: "PRI_Puerto Rico", value: "Puerto Rico", missing: ["_adm2","_adm3"] }, 
 { id: "GBR_United Kingdom", value: "United Kingdom", missing: ["_adm3"] }, 
 { id: "SPM_Saint Pierre and Miquelon", value: "Saint Pierre and Miquelon", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "GLP_Guadeloupe", value: "Guadeloupe", missing: ["_adm2","_adm3"] }, 
 { id: "MHL_Marshall Islands", value: "Marshall Islands", missing: ["_adm1","_adm2","_adm3","_rails","_roads","_water_areas_dcw"] }, 
 { id: "HRV_Croatia", value: "Croatia", missing: ["_adm3","_adm2"] }, 
 { id: "BFA_Burkina Faso", value: "Burkina Faso", missing: ["_adm3"] }, 
 { id: "CYP_Cyprus", value: "Cyprus", missing: ["_adm2","_adm3"] }, 
 { id: "TCA_Turks and Caicos Islands", value: "Turks and Caicos Islands", missing: ["_adm1","_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "DMA_Dominica", value: "Dominica", missing: ["_adm2","_adm3","_water_areas_dcw","_rails"] }, 
 { id: "QAT_Qatar", value: "Qatar", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "TWN_Taiwan", value: "Taiwan", missing: ["_adm3"] }, 
 { id: "USA_United States", value: "United States", missing: ["_adm3"] }, 
 { id: "BLR_Belarus", value: "Belarus", missing: ["_adm3"] }, 
 { id: "VUT_Vanuatu", value: "Vanuatu", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "VCT_Saint Vincent and the Grenadines", value: "Saint Vincent and the Grenadines", missing: ["_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "SMR_San Marino", value: "San Marino", missing: ["_adm2","_adm3","_water_areas_dcw"] }, 
 { id: "MRT_Mauritania", value: "Mauritania", missing: ["_adm3"] }, 
 { id: "COL_Colombia", value: "Colombia", missing: ["_adm3"] }, 
 { id: "LBY_Libya", value: "Libya", missing: ["_adm2","_adm3"] }, 
 { id: "DOM_Dominican Republic", value: "Dominican Republic", missing: ["_adm2","_adm3"] }, 
 { id: "ZWE_Zimbabwe", value: "Zimbabwe", missing: ["_adm3"] }, 
 { id: "IRQ_Iraq", value: "Iraq", missing: ["_adm3"] }, 
 { id: "GRC_Greece", value: "Greece", missing: ["_adm3"] }, 
 { id: "AUT_Austria", value: "Austria", missing: ["_adm3"] }, 
 { id: "WSM_Samoa", value: "Samoa", missing: ["_adm3","_rails","_water_areas_dcw"] }, 
 { id: "LCA_Santa Lucia", value: "Santa Lucia", missing: ["_adm2","_adm3","_water_areas_dcw"] }, 
 { id: "MUS_Mauritius", value: "Mauritius", missing: ["_adm2","_adm3"] }, 
 { id: "MTQ_Martinique", value: "Martinique", missing: ["_adm3","_water_areas_dcw"] }, 
 { id: "MYT_Mayotte", value: "Mayotte", missing: ["_adm2","_adm3","_rails","_water_areas_dcw"] }, 
 { id: "LIE_Liechtenstein", value: "Liechtenstein", missing: ["_adm2","_adm3","_water_areas_dcw"] }, 
 { id: "ECU_Ecuador", value: "Ecuador", missing: ["_adm1"] }, 
 { id: "CHE_Switzerland", value: "Switzerland", missing: ["_adm2","_adm3"] }, 
 { id: "SVK_Slovakia", value: "Slovakia", missing: ["_adm3"] }, 
 { id: "REU_Reunion", value: "Reunion", missing: ["_adm3","_water_areas_dcw"] }, 
 { id: "EGY_Egypt", value: "Egypt", missing: ["_adm2","_adm3"] }, 
 { id: "GRL_Greenland", value: "Greenland", missing: ["_adm3","_rails"] }, 
 { id: "SOM_Somalia", value: "Somalia", missing: ["_adm3"] }, 
 { id: "KGZ_Kyrgyzstan", value: "Kyrgyzstan", missing: ["_adm2","_adm3"] }, 
 { id: "MAC_Macao", value: "Macao", missing: ["_adm2","_adm3","_water_areas_dcw","_rails"] }, 
 { id: "KOR_South Korea", value: "South Korea", missing: ["_adm3"] }, 
 { id: "FSM_Micronesia,Federated States of ", value: "Micronesia,Federated States of ", missing: ["_adm2","_adm3","_water_areas_dcw","_rails"] }, 
 { id: "PCN_Pitcairn Islands", value: "Pitcairn Islands", missing: ["_adm3","_adm2","_adm1","_water_areas_dcw","_roads","_rails"] }, 
 { id: "SWZ_Swaziland", value: "Swaziland", missing: ["_adm2","_adm3"] }, 
 { id: "SYC_Seychelles", value: "Seychelles", missing: ["_adm2","_adm3","_water_areas_dcw","_rails"] }, 
 { id: "SYR_Syria", value: "Syria", missing: ["_adm2","_adm3"] }, 
 { id: "ROU_Romania", value: "Romania", missing: ["_adm3","_adm2","_water_areas_dcw","_roads","_rails"] }, 
 { id: "SLV_El Salvador", value: "El Salvador", missing: ["_adm3"] }, 
 { id: "RUS_Russian Federation", value: "Russian Federation", missing: ["_adm3"] }, 
 { id: "ISR_Israel", value: "Israel", missing: ["_adm2","_adm3"] }, 
 { id: "GUM_Guam", value: "Guam", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "MDA_Moldova", value: "Moldova", missing: ["_adm2","_adm3"] }, 
 { id: "SRB_Serbia", value: "Serbia", missing: ["_adm3"] }, 
 { id: "SWE_Sweden", value: "Sweden", missing: ["_adm3"] }, 
 { id: "GNQ_Equatorial Guinea", value: "Equatorial Guinea", missing: ["_adm2","_adm3"] }, 
 { id: "GIB_Gibraltar", value: "Gibraltar", missing: ["_adm2","_adm3","_roads","_water_areas_dcw","_rails"] }, 
 { id: "SLB_Solomon Islands", value: "Solomon Islands", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "RWA_Rwanda", value: "Rwanda", missing: ["_adm3","_rails"] }, 
 { id: "EST_Estonia", value: "Estonia", missing: ["_adm2","_adm3"] }, 
 { id: "NGA_Nigeria", value: "Nigeria", missing: ["_adm3"] }, 
 { id: "VGB_British Virgin Islands", value: "British Virgin Islands", missing: ["_adm3","_adm2","_water_areas_dcw","_rails"] }, 
 { id: "HKG_Hongkong", value: "Hongkong", missing: ["_adm2","_adm3","_water_areas_dcw"] }, 
 { id: "UKR_Ukraine", value: "Ukraine", missing: ["_adm3"] }, 
 { id: "POL_Poland", value: "Poland", missing: ["_adm3"] }, 
 { id: "BLZ_Belize", value: "Belize", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "PNG_Papua New Guinea", value: "Papua New Guinea", missing: ["_adm3","_rails"] }, 
 { id: "ARM_Armenia", value: "Armenia", missing: ["_adm2","_adm3"] }, 
 { id: "JAM_Jamaica", value: "Jamaica", missing: ["_adm2","_adm3"] }, 
 { id: "LKA_Sri Lanka", value: "Sri Lanka", missing: ["_adm3"] }, 
 { id: "ATF_French Southern Territories", value: "French Southern Territories", missing: ["_adm2","_adm3","_rails"] }, 
 { id: "BIH_Bosnia and Herzegovina", value: "Bosnia and Herzegovina", missing: ["_adm3"] },
 { id: "NAM_Namibia", value: "Namibia", missing: ["_adm3"] }, 
 { id: "LAO_Laos", value: "Laos", missing: ["_adm3","_rails"] },
 { id: "HND_Honduras", value: "Honduras", missing: ["_adm3"] }, 
 { id: "IRN_Iran", value: "Iran", missing: ["_adm3"] }, 
 { id: "CRI_Costa Rica", value: "Costa Rica", missing: ["_adm3"] },
 { id:'LSO_Lesotho', value:'Lesotho', missing:['_adm2','_adm3','_rails']},
 { id:'AUS_Australia', value:'Australia', missing:['_adm3']}
]);
